<?php

return [
    'name' => '模板',
    'beian' => '',
    'cdnurl' => '',
    'version' => '1.0.1',
    'timezone' => 'Asia/Shanghai',
    'forbiddenip' => '',
    'languages' => [
        'backend' => 'zh-cn',
        'frontend' => 'zh-cn',
    ],
    'fixedpage' => 'dashboard',
    'categorytype' => [
        'default' => 'Default',
        'page' => 'Page',
        'article' => 'Article',
        'test' => 'Test',
    ],
    'configgroup' => [
        'basic' => 'Basic',
        'sms' => '短信配置',
        'wechat' => '微信配置',
        'email' => 'Email',
        'dictionary' => 'Dictionary',
    ],
    'mail_type' => '1',
    'mail_smtp_host' => 'smtp.qq.com',
    'mail_smtp_port' => '465',
    'mail_smtp_user' => '10000',
    'mail_smtp_pass' => 'password',
    'mail_verify_type' => '2',
    'mail_from' => '10000@qq.com',
    'is_open_sms' => '1',
    'sms_platform' => 'aliyun',
    'sms_appid' => '',
    'sms_secret' => '',
    'sms_sign' => '',
    'sms_template' => [
        'login' => 'SMS_197095097',
    ],
    'wechat_mini_program_app_id' => '',
    'wechat_mini_program_secret' => '',
    'wechat_official_account_app_id' => '',
    'wechat_official_account_secret' => '',
    'wechat_payment_app_id' => '',
    'wechat_payment_mch_id' => '',
    'wechat_payment_key' => '',
    'wechat_notify_url' => '',
    'wechat_cert_path' => '',
    'wechat_key_path' => '',
];
